const menu = [
  {
    id: 1,
    title: 'aloo parantha',
    category: 'breakfast',
    price: 30.00,
    img: './images/item-1.webp',
    desc: `Aloo Paratha are popular Indian flatbreads stuffed with a delicious spiced potato mixture.  `,
  },
  {
    id: 2,
    title: 'butter chicken',
    category: 'lunch',
    price: 300.00,
    img: './images/item-2.webp',
    desc: ` Butter Chicken is a classic Indian dish thats made by simmering marinated & grilled chicken (Tandoori chicken). `,
  },
  {
    id: 3,
    title: 'mango lassi',
    category: 'shakes',
    price: 90.00,
    img: './images/item-3.webp',
    desc: `Mango lassi is a fruity variation of the popular classic sweet Lassi – a summer drink made with yogurt, water or milk, sugar and cardamoms.`,
  },
  {
    id: 4,
    title: 'idli',
    category: 'breakfast',
    price: 60.00,
    img: './images/item-4.webp',
    desc: `Idli or idly is a type of savoury rice cake, originating from South India, popular as a breakfast food in Southern India and in Sri Lanka. `,
  },
  {
    id: 5,
    title: 'paneer tikka',
    category: 'lunch',
    price: 280.00,
    img: './images/item-5.jpg',
    desc: ` Paneer tikka is an Indian dish made from chunks of paneer / chhena marinated in spices and grilled in a tandoor. `,
  },
  {
    id: 6,
    title: 'oreo milkshake',
    category: 'shakes',
    price: 120.00,
    img: './images/item-6.jpeg',
    desc: `Oreo milkshake should be on the summer menu of everyone who loves thick and creamy beverages.`,
  },
  {
    id: 7,
    title: 'dhokla',
    category: 'breakfast',
    price: 80.00,
    img: './images/item-7.jpg',
    desc: `Dhokla is a nutritious, steamed vegetarian gram flour snack from Gujarat in Western India, but it is popular all over the country.  `,
  },
  {
    id: 8,
    title: 'hyderabadi biryani',
    category: 'lunch',
    price: 280.00,
    img: './images/item-8.webp',
    desc: `Hyderabadi biryani is a style of biryani originating from Hyderabad, India made with basmati rice and meat.   `,
  },
  {
    id: 9,
    title: 'strawberry milkshake',
    category: 'shakes',
    price: 100.00,
    img: './images/item-9.jpg',
    desc: `Strawberry Milkshake is a delicious drink made with strawberries, milk, ice cream and flavoring ingredients like vanilla extract or strawberry syrup. `,
  },
];
export default menu;
